name: Deploy Fabric Operator to GKE
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write     # allow OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---- 1.  Authenticate to Google Cloud via OIDC ----
    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2.1.9
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    # ---- 2.  Fetch GKE credentials so kubectl/helm point to the cluster ----
    - name: Setup GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name:   ${{ secrets.CLUSTER_NAME }}
        location:       ${{ secrets.CLUSTER_REGION }}
        project_id:     ${{ secrets.PROJECT_ID }}

    # ---- 3.  Install or upgrade Helm + Fabric Operator chart ----
    - name: Install Helm
      uses: azure/setup-helm@v4       # lightweight helm installer

    - name: Add HLF Operator repo
      run: |
        helm repo add hlf-operator https://hyperledger-labs.github.io/fabric-operator/charts
        helm repo update

    - name: Helm upgrade --install
      run: |
        helm upgrade --install fabric-operator hlf-operator/fabric-operator \
          --version 0.10.0 \
          --namespace fabric-operator --create-namespace \
          --set image.tag=v0.10.0 \
          --set rbac.create=true
          --wait --timeout 5m

    # ---- 4.  (Optional) Apply org-specific CRDs/YAML from repo ----
    - name: Deploy Fabric components
      run: |
        kubectl apply -f k8s/ibpca-org1.yaml
        kubectl apply -f k8s/ibppeer-org1.yaml
        # add more manifests as you grow
